<template>
	<div class="Home">


		<div class="Home__title">

			<h1>
				Companies House API Demo
			</h1>

			<p>
				Based on this <a href="https://github.com/holistic-web/companies-house-demo" target="_blank">repo</a>
			</p>

			<h2>Usage</h2>

			<p>Once you have your API key, when on the page open the console and paste: </p>

			<blockquote>
				<p><code>localStorage.companiesHouseApiKey='YOUR-API-KEY'</code></p>
			</blockquote>

			<p>Where <code>YOUR-API-KEY</code> is the API key generated by the steps below. This will be used by all API
			calls made by the app.</p>

			<h2>API Guide</h2>

			<ol>
				<li><a href="https://developer.companieshouse.gov.uk/">API</a></li>

				<li>
					<a href="https://developer.companieshouse.gov.uk/api/docs/index/gettingStarted/quickStart.html#createaccount">
						Account Creation
					</a>
				</li>

				<li><a href="https://developer.companieshouse.gov.uk/developer/applications">API Key Generation</a></li>
			</ol>

		</div>

		<div class="Home__search">

			<b-input class="Home__search__term"
				v-model="searchTerm"
				ref="search"
				@keyup.enter.native="searchCompanies"/>

			<b-button class="Home__search__button"
				variant="primary"
				v-text="'Search'"
				@click.prevent="searchCompanies"/>

		</div>

		<b-container class="Home__companies">

			<company-card v-for="company in items"
				:key="company.company_number"
				:company="company"
				class="Home__companyCard"/>

		</b-container>

	</div>
</template>

<script>
import { mapActions, mapGetters } from 'vuex';
import CompanyCard from './CompanyCard';

export default {
	name: 'Home',
	components: {
		CompanyCard
	},
	data() {
		return {
			api: {
				url: 'https://api.companieshouse.gov.uk/'
			},
			searchTerm: 'abbey code'
		};
	},
	computed: {
		...mapGetters({
			items: 'searchCompaniesResults'
		})
	},
	created() {
		this.setApiKey();
		this.searchCompanies();
	},
	methods: {
		...mapActions({
			fetchCompanies: 'getCompaniesSearch'
		}),
		setApiKey() {
			if (!localStorage.companiesHouseApiKey) {
				// eslint-disable-next-line no-alert
				alert('Ensure you\'ve set your API key as localStorage.companiesHouseApiKey in browser console.');
			}
			this.api.config = {
				auth: {
					username: `${localStorage.companiesHouseApiKey}:`
				}
			};
		},
		searchCompanies() {
			this.fetchCompanies(this.searchTerm);
		}
		// async searchCompanies() {
		// 	const config = this.api.config;
		// 	config.params = {
		// 		q: this.searchTerm
		// 	};
		// 	const response = await this.$http.get(`${this.api.url}search/companies`, config);
		// 	this.items = response.data.items;
		// }
	}
};
</script>

<style lang="scss">
.Home {

	&__title {
		margin-left: 15px;
	}

	&__text {
		margin-left: 15px;
	}

	&__search {
		margin: auto;
		margin-bottom: 40px;
		float: left;
		position: relative;
		left: 50%;
		transform: translateX(-50%);

		&__term {
			float: left;
			width: 500px;
			margin-right: 16px;
		}

		&__button {
			float: left;
		}

	}

	&__companies {
		width: 100%;
		max-width: 100%;
		float: left;
	}

	&__companyCard {
		width: 23%;
		margin: 0 1% 32px 1%;
		display: inline-block;
		vertical-align: top;
	}
}
</style>
