branch-defaults:
  default:
    environment: e-ipbd6a4erd
    group_suffix: null
  master:
    environment: HolisticWebDeisgnCo-env
environment-defaults:
  HolisticWebDeisgnCo-env:
    branch: null
    repository: null
global:
  application_name: Holistic Web Deisgn Co
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
